version: '3'
services:
  serviceregistry:
    image: 'jusepe990324/serviceregistry:latest'
    container_name: service-registry
    ports:
      - '8761:8761'
  configserver:
    image: 'jusepe990324/configserver:latest'
    container_name: config-server
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
  cloudgateway:
    image: 'jusepe990324/cloudgateway:latest'
    container_name: cloud-gateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_ADDRESS=configserver
    depends_on:
      configserver:
        condition: service_healthy
