server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/product_db
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product-service
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
